# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter_manager_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConverterManagerWidget(object):
    def setupUi(self, ConverterManagerWidget):
        ConverterManagerWidget.setObjectName("ConverterManagerWidget")
        ConverterManagerWidget.resize(689, 346)
        self.gridLayout = QtWidgets.QGridLayout(ConverterManagerWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.converterList = QtWidgets.QListWidget(ConverterManagerWidget)
        self.converterList.setObjectName("converterList")
        self.gridLayout.addWidget(self.converterList, 0, 0, 1, 2)
        self.addConverterButton = QtWidgets.QPushButton(ConverterManagerWidget)
        self.addConverterButton.setObjectName("addConverterButton")
        self.gridLayout.addWidget(self.addConverterButton, 1, 0, 1, 1)
        self.deleteConverterButton = QtWidgets.QPushButton(ConverterManagerWidget)
        self.deleteConverterButton.setEnabled(False)
        self.deleteConverterButton.setObjectName("deleteConverterButton")
        self.gridLayout.addWidget(self.deleteConverterButton, 1, 1, 1, 1)

        self.retranslateUi(ConverterManagerWidget)
        QtCore.QMetaObject.connectSlotsByName(ConverterManagerWidget)

    def retranslateUi(self, ConverterManagerWidget):
        _translate = QtCore.QCoreApplication.translate
        ConverterManagerWidget.setWindowTitle(_translate("ConverterManagerWidget", "Form"))
        self.converterList.setToolTip(_translate("ConverterManagerWidget", "Select a file in the Export Mapper."))
        self.addConverterButton.setText(_translate("ConverterManagerWidget", "Add Converter"))
        self.deleteConverterButton.setText(_translate("ConverterManagerWidget", "Delete Converter"))
