# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export_mapper_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportMapperWidget(object):
    def setupUi(self, ExportMapperWidget):
        ExportMapperWidget.setObjectName("ExportMapperWidget")
        ExportMapperWidget.resize(758, 119)
        self.gridLayout = QtWidgets.QGridLayout(ExportMapperWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.promptForNewFileCheck = QtWidgets.QCheckBox(ExportMapperWidget)
        self.promptForNewFileCheck.setChecked(True)
        self.promptForNewFileCheck.setObjectName("promptForNewFileCheck")
        self.gridLayout.addWidget(self.promptForNewFileCheck, 2, 0, 1, 1)
        self.checkForBSSChangesButton = QtWidgets.QPushButton(ExportMapperWidget)
        self.checkForBSSChangesButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.checkForBSSChangesButton.setObjectName("checkForBSSChangesButton")
        self.gridLayout.addWidget(self.checkForBSSChangesButton, 2, 3, 1, 1)
        self.onlyOnChangesCheck = QtWidgets.QCheckBox(ExportMapperWidget)
        self.onlyOnChangesCheck.setChecked(False)
        self.onlyOnChangesCheck.setObjectName("onlyOnChangesCheck")
        self.gridLayout.addWidget(self.onlyOnChangesCheck, 2, 1, 1, 1)
        self.openBSSFolderButton = QtWidgets.QPushButton(ExportMapperWidget)
        self.openBSSFolderButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.openBSSFolderButton.setObjectName("openBSSFolderButton")
        self.gridLayout.addWidget(self.openBSSFolderButton, 2, 4, 1, 1)
        self.expandWholeTreeButton = QtWidgets.QPushButton(ExportMapperWidget)
        self.expandWholeTreeButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.expandWholeTreeButton.setObjectName("expandWholeTreeButton")
        self.gridLayout.addWidget(self.expandWholeTreeButton, 2, 2, 1, 1)
        self.exportMappingTree = QtWidgets.QTreeWidget(ExportMapperWidget)
        self.exportMappingTree.setToolTip("")
        self.exportMappingTree.setAlternatingRowColors(False)
        self.exportMappingTree.setIconSize(QtCore.QSize(24, 24))
        self.exportMappingTree.setWordWrap(True)
        self.exportMappingTree.setObjectName("exportMappingTree")
        self.exportMappingTree.header().setHighlightSections(False)
        self.gridLayout.addWidget(self.exportMappingTree, 0, 0, 1, 5)

        self.retranslateUi(ExportMapperWidget)
        QtCore.QMetaObject.connectSlotsByName(ExportMapperWidget)

    def retranslateUi(self, ExportMapperWidget):
        _translate = QtCore.QCoreApplication.translate
        ExportMapperWidget.setWindowTitle(_translate("ExportMapperWidget", "Form"))
        self.promptForNewFileCheck.setToolTip(_translate("ExportMapperWidget", "If unchecked, you can see this dialog again by clicking its app icon in windows."))
        self.promptForNewFileCheck.setText(_translate("ExportMapperWidget", "Prompt for Each New File"))
        self.checkForBSSChangesButton.setText(_translate("ExportMapperWidget", "Check for BSS Changes"))
        self.onlyOnChangesCheck.setToolTip(_translate("ExportMapperWidget", "If unchecked, you can see this dialog again by clicking its app icon in windows."))
        self.onlyOnChangesCheck.setText(_translate("ExportMapperWidget", "Export Only on Design Changes"))
        self.openBSSFolderButton.setText(_translate("ExportMapperWidget", "BSS Folder in Explorer..."))
        self.expandWholeTreeButton.setText(_translate("ExportMapperWidget", "Expand Whole Tree"))
        self.exportMappingTree.setSortingEnabled(True)
        self.exportMappingTree.headerItem().setText(0, _translate("ExportMapperWidget", "Input File"))
        self.exportMappingTree.headerItem().setToolTip(0, _translate("ExportMapperWidget", "Relative to your BSS export\'s root folder."))
        self.exportMappingTree.headerItem().setText(1, _translate("ExportMapperWidget", "File Changes"))
        self.exportMappingTree.headerItem().setText(2, _translate("ExportMapperWidget", "Process Option"))
        self.exportMappingTree.headerItem().setText(3, _translate("ExportMapperWidget", "Output File"))
        self.exportMappingTree.headerItem().setToolTip(3, _translate("ExportMapperWidget", "Relative to your Django project\'s root."))
        self.exportMappingTree.headerItem().setText(4, _translate("ExportMapperWidget", "Django URL"))
        self.exportMappingTree.headerItem().setToolTip(4, _translate("ExportMapperWidget", "The URL to access this resource in a Django template."))
        self.exportMappingTree.headerItem().setText(5, _translate("ExportMapperWidget", "Django View"))
        self.exportMappingTree.headerItem().setToolTip(5, _translate("ExportMapperWidget", "Name of the Django view function that loads this resource."))
        self.exportMappingTree.headerItem().setText(6, _translate("ExportMapperWidget", "Code Generation"))
        self.exportMappingTree.headerItem().setToolTip(6, _translate("ExportMapperWidget", "Boilerplate code generation options.  Click buttons to go to the code."))
